### PR TITLE
Add support for Alternate Registries

### PR DESCRIPTION
**Pull request by BarbossHack**
Add support for alternate registries, as discussed in https://github.com/serayuzgur/crates/pull/217#issuecomment-1975172827 :

- Read alternate registries from ~/.cargo/config.toml (or ~/.cargo/config for legacy) if any.
- Read registry tokens from ~/.cargo/credentials.toml if any.
- Support registry authentification with cargo:token credentials.
- Does not support registry authenfication with cargo:libsecret, cargo:macos-keychain, cargo:wincred. Support may be added later.
- Decorator (mouseover popup) fields View Crate, Check review and Doc are hidden for crates that are on alternate registries.
- Default behavior is to ignore crates that have an alternate registry :
    - If a crate have an alternate registry, but it could not be found in config.toml, just ignore it without error, and do NOT use indexServerURL as a fallback registry.
    - If the registry is found, then fetch versions on this registry.
- I've added a script (./sample/alternate-registry.sh) to facilitate testing with alternate registries, for development purposes only.

Other modifications :

- I removed src/api/crates-index-server.ts as it was not used anymore
- I removed isSparseCompatible() as it was not used anymore

Fixes https://github.com/serayuzgur/crates/issues/213
Fixes https://github.com/serayuzgur/crates/issues/182

### CODE REVIEW

**Comment by BarbossHack** [comment]
Fixes https://github.com/serayuzgur/crates/pull/233

**Comment by BarbossHack** [comment]
Fixes https://github.com/serayuzgur/crates/pull/232

**Comment by BarbossHack** [comment]
Fixes https://github.com/serayuzgur/crates/pull/217

**Comment by serayuzgur** [comment]
Hello, 
Congratulations for these features . As you can see, I rebrand the extension now we got more language support refactored all the code and more.

You can also check the new code base if it is compatible what you did or not. 
If you have any questions, you are welcome

**Pull request merged**
